Create new permission api with validations
ELEVATE-Project/sl-backend-automation pull request #59
Opened 2024-10-20 18:22 UTC by subash-cs

2024-10-21 01:19 UTC, infa-rvarahag requested changes

2024-10-21 01:19 UTC, infa-rvarahag commented on SanitySuiteSCP_API.xml
class name should be  : TestSCPermissionCRUPOperations
xml syntax should be like this :
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="SanitySuite">

    <test name="Test">
        <classes>

            <class name="org.shikshalokam.backend.ep.CLASSNAME">
                <methods>
                    <include name="TestMethodNames1"/>
                    <include name="TestMethodNames1"/>
                    <include name="TestMethodNames1"/>
                </methods>
            </class>

        </classes>
    </test> <!-- Test -->
</suite> <!-- Suite -->

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
>              RestAssured.baseURI = PropertyLoader.PROP_LIST.get("scp.qa.api.base.url").toString();
This already we are doing in the base call hence it is not required again here . Remove this

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +                "\"code\": \"project_test_break\", " +
Please use code like this to create a Json object and pass the same as body to the request 

JSONObject jsonObject = new JSONObject();

        // Add key-value pairs
        jsonObject.put("name", "John Doe");
        jsonObject.put("age", 30);
        jsonObject.put("email", "johndoe@example.com");
        jsonObject.put("isMarried", false);

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +        logger.info("Ended calling the CreatePermission API with valid payload.");
Please add 
assertEquals to validate response code .
fetch responce and validate ID 
No assertions

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +        String requestBody = "{ " +
Remove String and add Json Object structure

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +            RestAssured.baseURI = PropertyLoader.PROP_LIST.get("scp.qa.api.base.url").toString();
Remove this , this is not required , while login base URL already assigned by extended class

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +
Please validate the response messages . code using TestNG assertions

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +            RestAssured.baseURI = PropertyLoader.PROP_LIST.get("scp.qa.api.base.url").toString();
Remove this not required

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
> +        String requestBody = "{ " +
Convert to JsonObject , remove string

2024-10-21 01:19 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/SelfCreationPortalCreateNewPermission.java
Please add assertions to the response using testNG

2024-10-22 04:47 UTC, infa-rvarahag requested changes

2024-10-22 04:47 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpPermissionCRUDOperations.java
Move the Base url assignment to  Base class 
Remove the code for fetching internal access token and start using the base class assigned token X_AUTH_TOKEN

2024-10-22 04:47 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpPermissionCRUDOperations.java
> +    //Method to generate random word as code(Project name)
RandomStringUtils.randomAlphabetic(20) use this method .Bulit in methods more optimized

2024-10-22 04:47 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpPermissionCRUDOperations.java
write a common method  for the Respsonce createpermission ( JsonObject  object )

then start using this in all Test methods and validate the response written

2024-10-22 04:47 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpPermissionCRUDOperations.java
Move all non test methods to the end of the class

2024-10-22 04:47 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpPermissionCRUDOperations.java
move to Backend

2024-10-22 06:22 UTC, subash-cs reviewed
Comments done

2024-10-22 12:40 UTC, infa-rvarahag approved these changes

2024-10-22 12:43 UTC, merged