Entities crud operations
ELEVATE-Project/sl-backend-automation pull request #78
Opened 2024-10-29 12:28 UTC by subash-cs

2024-10-30 04:58 UTC, infa-rvarahag requested changes

2024-10-30 04:58 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpEntityTypesAndEntitiesCRUDOperations.java
> +    @Test(dependsOnMethods = "testCreateEntityTypeWithInValidPayload", description = "Verifies the functionality of creating new entity with valid payload.")
No need of this dependency

2024-10-30 04:58 UTC, infa-rvarahag commented on src/test/java/org/shikshalokam/backend/scp/TestScpEntityTypesAndEntitiesCRUDOperations.java
> +    @Test(dependsOnMethods = "testCreateEntityTypeWithEmptyFields", description = "Verifies the functionality of creating new entity with valid payload.")
No need of this dependency

2024-11-04 15:00 UTC, subash-cs commented on src/test/java/org/shikshalokam/backend/scp/TestScpEntityTypesAndEntitiesCRUDOperations.java
> +    @Test(dependsOnMethods = "testCreateEntityTypeWithInValidPayload", description = "Verifies the functionality of creating new entity with valid payload.")
done

2024-11-04 15:00 UTC, subash-cs commented on src/test/java/org/shikshalokam/backend/scp/TestScpEntityTypesAndEntitiesCRUDOperations.java
> +    @Test(dependsOnMethods = "testCreateEntityTypeWithEmptyFields", description = "Verifies the functionality of creating new entity with valid payload.")
done

2024-11-06 00:55 UTC, infa-rvarahag approved these changes
Assert.assertTrue(statusCode == 400 || statusCode == 422, "Status code should be 400 or 422 for invalid payload");
  This type of validations not correct. Next submit correct the same .

2024-11-06 03:51 UTC, subash-cs commented
> Assert.assertTrue(statusCode == 400 || statusCode == 422, "Status code should be 400 or 422 for invalid payload"); This type of validations not correct. Next submit correct the same .

Yeah,noted

2024-11-06 03:51 UTC, merged